import type { DocTable, GeneratedDocs } from './types.ts'
import { useLoad } from './useLoad.ts'

function rows(count: number | null): string {
  return count === null ? 'row count unknown' : `${count.toLocaleString('en-US')} rows`
}

function TableDoc({ table }: { table: DocTable }) {
  const id = `doc-${table.qualified_name.replace(/[^a-zA-Z0-9_-]/g, '-')}`
  return (
    <section className="card doc-table" aria-labelledby={id}>
      <div className="card-head">
        <h3 id={id}>
          <code>{table.qualified_name}</code>
        </h3>
        <span className="muted">
          {table.kind} · {rows(table.estimated_row_count)}
        </span>
      </div>
      {table.comment && <p className="muted">{table.comment}</p>}
      <dl className="facts">
        <dt>Primary key</dt>
        <dd>{table.primary_key.length ? table.primary_key.join(', ') : '—'}</dd>
        <dt>Relationships</dt>
        <dd>
          {table.foreign_keys.length === 0
            ? '—'
            : table.foreign_keys.map((fk) => (
                <span className="fk" key={`${fk.columns.join(',')}-${fk.referred_table}`}>
                  {fk.columns.join(', ')} → {fk.referred_table}.{fk.referred_columns.join(', ')}
                </span>
              ))}
        </dd>
      </dl>
      <div className="table-wrap">
        <table>
          <thead>
            <tr>
              <th scope="col">Column</th>
              <th scope="col">Type</th>
              <th scope="col">Nullable</th>
              <th scope="col">Allowed values</th>
              <th scope="col">Sample values</th>
            </tr>
          </thead>
          <tbody>
            {table.columns.map((column) => (
              <tr key={column.name}>
                <td>
                  <code>{column.name}</code>
                </td>
                <td>{column.data_type}</td>
                <td>{column.nullable ? 'yes' : 'no'}</td>
                <td>{column.allowed_values?.length ? column.allowed_values.join(', ') : '—'}</td>
                <td>{column.sample_values.length ? column.sample_values.join(', ') : '—'}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </section>
  )
}

/** Generated warehouse docs: read-only, raw schema metadata plus policy-permitted samples. */
export function DocsView() {
  const { data, error } = useLoad<GeneratedDocs>('/api/semantic/docs')

  if (error) return <p className="error" role="alert">{error}</p>
  if (!data) return <p className="muted">Loading…</p>
  if (data.tables.length === 0) {
    return <p className="muted">Nothing crawled yet. Run the crawler to generate warehouse docs.</p>
  }
  return (
    <div className="stack">
      <p className="muted">
        Generated by the crawler and read-only. Sample values are shown only for columns the
        sampling policy permits; business meaning belongs in Business context.
      </p>
      {data.tables.map((table) => (
        <TableDoc key={table.qualified_name} table={table} />
      ))}
    </div>
  )
}
