import { useState, type FormEvent } from 'react'
import { api } from '../api/client.ts'
import type { ListOf } from '../api/types.ts'
import { failureFrom, type Failure } from './failure.ts'
import { ProblemAlert } from './ProblemAlert.tsx'
import type { UseCase, UseCaseStatus } from './types.ts'
import { useLoad } from './useLoad.ts'

const STATUS_LABELS: Record<UseCaseStatus, string> = {
  needs_rereview: 'Needs re-review',
  pending_review: 'Pending review',
  confirmed: 'Confirmed',
  rejected: 'Rejected',
}

// Flagged items first: they were confirmed and the warehouse changed underneath them.
const ORDER: UseCaseStatus[] = ['needs_rereview', 'pending_review', 'confirmed', 'rejected']

function sorted(items: UseCase[]): UseCase[] {
  return [...items].sort((a, b) => ORDER.indexOf(a.status) - ORDER.indexOf(b.status) || a.id - b.id)
}

function UseCaseEditor({
  useCase,
  onSaved,
  onCancel,
}: {
  useCase: UseCase
  onSaved: () => void
  onCancel: () => void
}) {
  const [request, setRequest] = useState(useCase.nl_request)
  const [spec, setSpec] = useState(JSON.stringify(useCase.spec, null, 2))
  const [failure, setFailure] = useState<Failure | null>(null)
  const [busy, setBusy] = useState(false)

  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault()
    let parsed: unknown
    try {
      parsed = JSON.parse(spec)
    } catch {
      setFailure({ message: 'Spec must be valid JSON.', problems: [] })
      return
    }
    setBusy(true)
    setFailure(null)
    try {
      await api(`/api/semantic/use-cases/${useCase.id}`, {
        method: 'PUT',
        body: { nl_request: request, spec: parsed },
      })
      onSaved()
    } catch (err) {
      setFailure(failureFrom(err))
    } finally {
      setBusy(false)
    }
  }

  return (
    <form className="stack" aria-label={`Edit use case ${useCase.id}`} onSubmit={(e) => void submit(e)}>
      {failure && <ProblemAlert failure={failure} />}
      <label className="field">
        <span>Request</span>
        <input required value={request} onChange={(e) => setRequest(e.target.value)} />
      </label>
      <label className="field">
        <span>Spec (JSON)</span>
        <textarea
          className="code"
          rows={10}
          spellCheck={false}
          value={spec}
          onChange={(e) => setSpec(e.target.value)}
        />
      </label>
      <p className="hint">Saving makes this a human-authored, confirmed use case; later crawls leave it alone.</p>
      <div className="actions">
        <button type="button" className="quiet" onClick={onCancel}>
          Cancel
        </button>
        <button type="submit" disabled={busy}>
          Save and confirm
        </button>
      </div>
    </form>
  )
}

function UseCaseCard({
  useCase,
  canReview,
  onChanged,
}: {
  useCase: UseCase
  canReview: boolean
  onChanged: () => void
}) {
  const [editing, setEditing] = useState(false)
  const [failure, setFailure] = useState<Failure | null>(null)
  const [busy, setBusy] = useState(false)

  async function decide(action: 'confirm' | 'reject') {
    setBusy(true)
    setFailure(null)
    try {
      await api(`/api/semantic/use-cases/${useCase.id}/${action}`, { method: 'POST' })
      onChanged()
    } catch (err) {
      setFailure(failureFrom(err))
    } finally {
      setBusy(false)
    }
  }

  const flagged = useCase.status === 'needs_rereview'
  return (
    <article className={flagged ? 'card use-case needs-rereview' : 'card use-case'}>
      <div className="card-head">
        <h3>{useCase.nl_request}</h3>
        <span className={`status status-${useCase.status}`}>{STATUS_LABELS[useCase.status]}</span>
      </div>
      <p className="muted small">
        {useCase.origin === 'human' ? 'Written by a person' : 'Generated by the crawler'}
        {useCase.reviewed_by ? ` · reviewed by ${useCase.reviewed_by.display_name}` : ''}
      </p>
      {useCase.review_note && <p className="warning">{useCase.review_note}</p>}
      {useCase.rewritten_from && (
        <p className="muted small">
          Rewritten from “{useCase.rewritten_from}”{useCase.generation_note ? `: ${useCase.generation_note}` : ''}
        </p>
      )}
      <details>
        <summary>Spec</summary>
        <pre className="code-block">{JSON.stringify(useCase.spec, null, 2)}</pre>
      </details>
      {failure && <ProblemAlert failure={failure} />}
      {canReview && !editing && (
        <div className="actions">
          {useCase.status !== 'confirmed' && (
            <button type="button" disabled={busy} onClick={() => void decide('confirm')}>
              Confirm
            </button>
          )}
          <button type="button" className="quiet" disabled={busy} onClick={() => setEditing(true)}>
            Edit
          </button>
          {useCase.status !== 'rejected' && (
            <button type="button" className="quiet danger" disabled={busy} onClick={() => void decide('reject')}>
              Reject
            </button>
          )}
        </div>
      )}
      {editing && (
        <UseCaseEditor
          useCase={useCase}
          onSaved={() => {
            setEditing(false)
            onChanged()
          }}
          onCancel={() => setEditing(false)}
        />
      )}
    </article>
  )
}

/** Example use cases: only confirmed ones ever reach the cohort assistant (BR-7). */
export function UseCaseQueue({ canReview, onChanged }: { canReview: boolean; onChanged: () => void }) {
  const [status, setStatus] = useState<'' | UseCaseStatus>('')
  const { data, error, reload } = useLoad<ListOf<UseCase>>('/api/semantic/use-cases', { status })

  function changed() {
    reload()
    onChanged()
  }

  return (
    <div className="stack">
      <p className="muted">
        Example requests the crawler generated from your data, plus human-edited ones. Pending items are never
        used until confirmed.
      </p>
      <label className="field narrow">
        <span>Show</span>
        <select value={status} onChange={(e) => setStatus(e.target.value as '' | UseCaseStatus)}>
          <option value="">All</option>
          {ORDER.map((s) => (
            <option key={s} value={s}>
              {STATUS_LABELS[s]}
            </option>
          ))}
        </select>
      </label>
      {error && (
        <p className="error" role="alert">
          {error}
        </p>
      )}
      {!data && !error && <p className="muted">Loading…</p>}
      {data && data.items.length === 0 && <p className="muted">No use cases here.</p>}
      {data &&
        sorted(data.items).map((useCase) => (
          <UseCaseCard key={useCase.id} useCase={useCase} canReview={canReview} onChanged={changed} />
        ))}
    </div>
  )
}
